#!/bin/bash

###############################################################################
# Pantheon AI Platform - Automated Installation Script
# 
# This script automatically installs and configures Pantheon on any machine
# with Docker and Docker Compose installed.
#
# Usage:
#   bash install-pantheon.sh
#
# Requirements:
#   - Docker 20.10+
#   - Docker Compose 2.0+
#   - Internet connection
#   - 20GB free disk space
###############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PANTHEON_VERSION="1.0.0"
DOCKER_HUB_USER="akilhassane"
REQUIRED_DOCKER_VERSION="20.10"
REQUIRED_COMPOSE_VERSION="2.0"

# Print colored output
print_info() {
    echo -e "${BLUE}ℹ ${1}${NC}"
}

print_success() {
    echo -e "${GREEN}✓ ${1}${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ ${1}${NC}"
}

print_error() {
    echo -e "${RED}✗ ${1}${NC}"
}

print_header() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Compare version numbers
version_ge() {
    printf '%s\n%s\n' "$2" "$1" | sort -V -C
}

# Check system requirements
check_requirements() {
    print_header "Checking System Requirements"
    
    local all_ok=true
    
    # Check Docker
    if command_exists docker; then
        DOCKER_VERSION=$(docker --version | grep -oP '\d+\.\d+' | head -1)
        if version_ge "$DOCKER_VERSION" "$REQUIRED_DOCKER_VERSION"; then
            print_success "Docker $DOCKER_VERSION installed"
        else
            print_error "Docker version $DOCKER_VERSION is too old. Required: $REQUIRED_DOCKER_VERSION+"
            all_ok=false
        fi
    else
        print_error "Docker is not installed"
        print_info "Install Docker from: https://docs.docker.com/get-docker/"
        all_ok=false
    fi
    
    # Check Docker Compose
    if command_exists docker-compose || docker compose version >/dev/null 2>&1; then
        if command_exists docker-compose; then
            COMPOSE_VERSION=$(docker-compose --version | grep -oP '\d+\.\d+' | head -1)
        else
            COMPOSE_VERSION=$(docker compose version | grep -oP '\d+\.\d+' | head -1)
        fi
        
        if version_ge "$COMPOSE_VERSION" "$REQUIRED_COMPOSE_VERSION"; then
            print_success "Docker Compose $COMPOSE_VERSION installed"
        else
            print_error "Docker Compose version $COMPOSE_VERSION is too old. Required: $REQUIRED_COMPOSE_VERSION+"
            all_ok=false
        fi
    else
        print_error "Docker Compose is not installed"
        print_info "Install Docker Compose from: https://docs.docker.com/compose/install/"
        all_ok=false
    fi
    
    # Check disk space
    AVAILABLE_SPACE=$(df -BG . | awk 'NR==2 {print $4}' | sed 's/G//')
    if [ "$AVAILABLE_SPACE" -ge 20 ]; then
        print_success "Sufficient disk space available (${AVAILABLE_SPACE}GB)"
    else
        print_warning "Low disk space: ${AVAILABLE_SPACE}GB available (20GB recommended)"
    fi
    
    # Check internet connection
    if ping -c 1 google.com >/dev/null 2>&1; then
        print_success "Internet connection available"
    else
        print_error "No internet connection detected"
        all_ok=false
    fi
    
    if [ "$all_ok" = false ]; then
        print_error "System requirements not met. Please install missing dependencies."
        exit 1
    fi
    
    echo ""
}

# Create environment file
create_env_file() {
    print_header "Creating Environment Configuration"
    
    if [ -f .env ]; then
        print_warning ".env file already exists"
        read -p "Do you want to overwrite it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_info "Keeping existing .env file"
            return
        fi
    fi
    
    print_info "Creating .env file..."
    
    cat > .env << 'EOF'
# Pantheon AI Platform - Environment Configuration
# Generated by install-pantheon.sh

# ============================================================================
# SUPABASE CONFIGURATION (Required)
# ============================================================================
# Get these from your Supabase project: https://supabase.com/dashboard
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key-here
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here

# Public Supabase configuration (for frontend)
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here

# ============================================================================
# AI PROVIDER API KEYS (At least one required)
# ============================================================================
# OpenAI (Recommended for GPT-4, GPT-4o, o1)
OPENAI_API_KEY=

# Anthropic (For Claude models)
ANTHROPIC_API_KEY=

# Google Gemini (For Gemini models)
GEMINI_API_KEY=

# OpenRouter (Alternative provider for multiple models)
OPENROUTER_API_KEY=

# Mistral AI
MISTRAL_API_KEY=

# Cohere
COHERE_API_KEY=

# ============================================================================
# BACKEND CONFIGURATION
# ============================================================================
PORT=3002
NODE_ENV=production
DEBUG=false

# Backend API URL (for frontend)
NEXT_PUBLIC_API_URL=http://localhost:3002

# ============================================================================
# MCP CONFIGURATION (Advanced)
# ============================================================================
# Master secret for generating per-project API keys
# Generate with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
MCP_MASTER_SECRET=

# Windows VM host (for Windows projects)
WINDOWS_MCP_HOST=host.docker.internal

# Host path for Windows VM files (Docker-in-Docker)
HOST_WINDOWS_VM_FILES_PATH=/app/windows-vm-files

# ============================================================================
# OPTIONAL CONFIGURATION
# ============================================================================
# Analytics ID (optional)
ANALYTICS_ID=

EOF
    
    print_success ".env file created"
    print_warning "Please edit .env file and add your Supabase credentials and API keys"
    echo ""
}

# Pull Docker images
pull_images() {
    print_header "Pulling Docker Images from Docker Hub"
    
    print_info "This may take 10-20 minutes depending on your internet speed..."
    echo ""
    
    local images=(
        "frontend"
        "backend"
        "windows-tools-api"
    )
    
    for image in "${images[@]}"; do
        print_info "Pulling ${DOCKER_HUB_USER}/pantheon:${image}..."
        if docker pull "${DOCKER_HUB_USER}/pantheon:${image}"; then
            print_success "Successfully pulled ${image}"
        else
            print_error "Failed to pull ${image}"
            exit 1
        fi
        echo ""
    done
    
    print_success "All images pulled successfully"
    echo ""
}

# Start services
start_services() {
    print_header "Starting Pantheon Services"
    
    print_info "Starting containers with docker-compose..."
    
    if docker compose -f docker-compose.production.yml up -d; then
        print_success "Services started successfully"
    else
        print_error "Failed to start services"
        exit 1
    fi
    
    echo ""
    print_info "Waiting for services to be healthy..."
    sleep 10
    
    # Check service health
    local all_healthy=true
    
    if docker ps | grep -q "pantheon-frontend"; then
        print_success "Frontend is running"
    else
        print_error "Frontend failed to start"
        all_healthy=false
    fi
    
    if docker ps | grep -q "pantheon-backend"; then
        print_success "Backend is running"
    else
        print_error "Backend failed to start"
        all_healthy=false
    fi
    
    if docker ps | grep -q "pantheon-windows-tools"; then
        print_success "Windows Tools API is running"
    else
        print_error "Windows Tools API failed to start"
        all_healthy=false
    fi
    
    if [ "$all_healthy" = false ]; then
        print_error "Some services failed to start. Check logs with: docker-compose logs"
        exit 1
    fi
    
    echo ""
}

# Run health checks
run_health_checks() {
    print_header "Running Health Checks"
    
    print_info "Checking frontend health..."
    if curl -f http://localhost:3000 >/dev/null 2>&1; then
        print_success "Frontend is healthy"
    else
        print_warning "Frontend health check failed (may still be starting)"
    fi
    
    print_info "Checking backend health..."
    if curl -f http://localhost:3002/health >/dev/null 2>&1; then
        print_success "Backend is healthy"
    else
        print_warning "Backend health check failed (may still be starting)"
    fi
    
    print_info "Checking Windows Tools API health..."
    if curl -f http://localhost:3003/health >/dev/null 2>&1; then
        print_success "Windows Tools API is healthy"
    else
        print_warning "Windows Tools API health check failed (may still be starting)"
    fi
    
    echo ""
}

# Print success message
print_completion() {
    print_header "Installation Complete!"
    
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                                                           ║${NC}"
    echo -e "${GREEN}║  🎉 Pantheon AI Platform is now running!                 ║${NC}"
    echo -e "${GREEN}║                                                           ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    print_info "Access Pantheon at:"
    echo "  🌐 Frontend:         http://localhost:3000"
    echo "  🔧 Backend API:      http://localhost:3002"
    echo "  🪟 Windows Tools:    http://localhost:3003"
    echo ""
    
    print_info "Next steps:"
    echo "  1. Edit .env file with your Supabase credentials and API keys"
    echo "  2. Restart services: docker-compose -f docker-compose.production.yml restart"
    echo "  3. Open http://localhost:3000 in your browser"
    echo "  4. Create an account and start using Pantheon!"
    echo ""
    
    print_info "Useful commands:"
    echo "  • View logs:         docker-compose -f docker-compose.production.yml logs -f"
    echo "  • Stop services:     docker-compose -f docker-compose.production.yml down"
    echo "  • Restart services:  docker-compose -f docker-compose.production.yml restart"
    echo "  • Update images:     docker-compose -f docker-compose.production.yml pull"
    echo ""
    
    print_info "Documentation:"
    echo "  • User Guide:        ./docs/USER_GUIDE.md"
    echo "  • API Reference:     ./docs/API_REFERENCE.md"
    echo "  • Troubleshooting:   ./docs/TROUBLESHOOTING.md"
    echo ""
    
    print_warning "IMPORTANT: Don't forget to configure your .env file!"
    echo ""
}

# Main installation flow
main() {
    clear
    
    echo -e "${BLUE}"
    cat << "EOF"
    ____              __  __                     
   / __ \____ _____  / /_/ /_  ___  ____  ____  
  / /_/ / __ `/ __ \/ __/ __ \/ _ \/ __ \/ __ \ 
 / ____/ /_/ / / / / /_/ / / /  __/ /_/ / / / / 
/_/    \__,_/_/ /_/\__/_/ /_/\___/\____/_/ /_/  
                                                 
    Multi-Agentic AI Platform
    Version 1.0.0
    
EOF
    echo -e "${NC}"
    
    print_info "This script will install Pantheon AI Platform on your system"
    print_info "Installation will take approximately 10-20 minutes"
    echo ""
    
    read -p "Press Enter to continue or Ctrl+C to cancel..."
    echo ""
    
    check_requirements
    create_env_file
    pull_images
    start_services
    run_health_checks
    print_completion
}

# Run main function
main
