$filesToMove = @(
    'aggressive-compact-docker.ps1', 'aggressive.json', 'aggressive.png',
    'all-elements-test.png', 'all-elements.json',
    'analyze-docker-window.py', 'analyze-screenshot-data.cjs', 'analyze-screenshot-simple.py',
    'analyze-taskbar-visual.py', 'analyze-youtube-search-bar.cjs',
    'api-docs.html', 'apply-custom-modes-migration.cjs',
    'ask-ai-whats-on-screen.cjs', 'ask-gemini-about-screen.cjs',
    'check-all-custom-modes.cjs', 'check-all-taskbar-detection.py',
    'check-collaborators-db.cjs', 'check-database-schema.cjs',
    'check-latest-custom-modes.cjs', 'check-localStorage-modes.cjs',
    'check-new-mode.cjs', 'check-project-keys.cjs',
    'check-screenshot-data.py', 'check-supabase-data.js',
    'check-taskbar.py', 'check-user-avatars-api.cjs',
    'check-user-avatars-sql.cjs', 'check-user-avatars.cjs',
    'clear-session-data.cjs', 'compact-docker-simple.ps1',
    'compact-docker-vhdx.ps1', 'compact-vhdx.ps1',
    'complete.json', 'complete.png',
    'count-names.py', 'count-taskbar-icons.py',
    'create-user-and-transfer-project.cjs',
    'current-docker.json', 'current-docker.png',
    'current-screen.json', 'current-screen.png', 'current-screenshot.png',
    'decode-screenshot.cjs', 'decode-screenshot.py',
    'deployment-test.png', 'describe-screenshot.py',
    'detailed-taskbar-scan.py', 'detect-all-taskbar-icons.py',
    'detect-pinned-apps.py', 'detect-taskbar-icons-visual.py',
    'direct-screenshot-click-edge.cjs',
    'docker-160512.json', 'docker-160512.png',
    'docker-focused.json', 'docker-focused.png',
    'docker-now-160502.png', 'docker-now.json', 'docker-now.png',
    'docker-screen.json', 'docker-screen.png',
    'emergency-cleanup.js', 'enhanced-test.json', 'enhanced-test.png',
    'extract-search-coords.cjs', 'final-complete-test.cjs',
    'find-all-bottom-elements.py', 'find-and-click-copilot.py',
    'find-best-free-model.cjs', 'find-desktop-edge-icon.cjs',
    'find-desktop-recycle-bin.py', 'find-docker-extensions.py',
    'find-docker-menuitems.py', 'find-recycle-bin.py',
    'find-system-tray-ui-elements.py', 'find-youtube-search-elements.cjs',
    'fix-owner-profile-and-hello-mode.cjs', 'fix-windows-ports-postgres.cjs',
    'fix-windows-ports.cjs', 'fix-windows-project-connection.cjs',
    'fix-windows-terminal.cjs', 'formatted-data.txt',
    'free-models-test-results.txt', 'fresh-docker.json', 'fresh-docker.png',
    'fresh.json', 'fresh.png', 'full-backend-logs.txt',
    'generate-screenshot-json.py', 'get-taskbar-icons-pywinauto.py',
    'get-taskbar-icons-uia.py', 'import-existing-windows-project.cjs',
    'install-keycloak-dependencies.cjs', 'latest-logs.txt',
    'list-all-taskbar-elements.py', 'list-gemini-models.cjs',
    'list-openrouter-free-models-new.cjs', 'list-openrouter-free-models.js',
    'now.png', 'nvidia-backend-logs.txt', 'nvidia-final-test.txt',
    'nvidia-test-output.txt', 'open-and-click-edge-window.cjs',
    'query-project-api-key.cjs', 'raw-screenshot-data.json',
    'raw-screenshot-data.txt', 'restore-terminal-port.cjs',
    'screen-data-full.txt', 'screenshot-analysis.txt',
    'screenshot-decoded.png', 'screenshot-docker.txt', 'screenshot-local.py',
    'set-correct-terminal-port.cjs', 'show-all-screen-elements.py',
    'show-taskbar-only.py', 'show-taskbar.py',
    'sync-avatars-from-supabase-auth.cjs', 'sync-custom-modes-localStorage.cjs',
    'sync-google-user.cjs', 'taskbar-only.png', 'taskbar-test.json',
    'tree-walk.json', 'tree-walk.png',
    'ui_elements.json', 'ui_elements_output.json',
    'update-mcp-api-key.cjs', 'update-vnc-url.cjs',
    'verify-optimization.cjs', 'windows-api-content.html',
    'windows-tools-api-server.js', 'youtube-search-raw.json'
)

foreach($file in $filesToMove) {
    if(Test-Path $file) {
        Write-Host "Moving: $file"
        git mv $file screenshots/
    }
}
